import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import { Providers } from "@/global_state/provider";
import { Toaster } from "react-hot-toast";

const vazir = Vazirmatn({
  variable: "--font-vazir-sans",
  subsets: ["latin", "arabic"],
});

export const metadata: Metadata = {
  title: "own | shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazir.variable} `}>
        <Providers>
          <Toaster
            toastOptions={{
              className: "",
              style: {
                padding: "16px",
                fontSize: "16px",
              },
            }}
          />
          {children}
        </Providers>
      </body>
    </html>
  );
}
